name: Create SAP Build
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create SAP Build
      if: ${{ env.GIT_BRANCH == 'develop' }}
      run: echo "Good to deploy! ${{ env.GIT_BRANCH }}"
