name: Create SAP Build
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Git Branch
      run: echo "Branch details  ${{ github.ref }} $GITHUB_REF $GITHUB_SHA ${{ steps.extract_branch.outputs.branch }} $GITHUB_HEAD_REF"
    - name: Create SAP Build
      if: endsWith(github.ref, 'develop') == true
      run: echo "Good to deploy! ${{ env.GIT_BRANCH }}"
