name: Create SAP Build
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Git Branch
      run: echo "Branch details  ${{ github.ref }} $GITHUB_REF $GITHUB_SHA"
    - name: Create SAP Build
      if: endsWith(github.ref, 'develop') == true
      run: echo "Good to deploy! ${{ env.GIT_BRANCH }}"
