name: Create SAP Build
on:
  push:
    branches:
      - master
      - develop
      - hotfix
      - release
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Git Show Tag Details
      run: git show $GITHUB_REF
    - name: Git Branch
      run: echo "Branch details  ${{ github.ref }} $GITHUB_REF $GITHUB_SHA ${{ steps.extract_branch.outputs.branch }} $GITHUB_HEAD_REF"
    - name: Create SAP Build
      if: endsWith(github.ref, 'develop')
      run: echo "branch endsWith develop :! ${{ env.GIT_BRANCH }}"
