name: BUILD_APP
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - develop
      - hotfix
      - release
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "The event name is ${{ github.event_name }}"
        #echo "$GITHUB_CONTEXT"
    - name: Set ENV Variables
      run: ./.github/scripts/set-env-variables.ps1
      shell: pwsh
    - run: env
