name: deploy-to-dev-cms-vercel
on:
  workflow_dispatch:
    inputs:
      Name:
        type: choice
        description: Whom to greet
        options: 
        - User1
        - User2
      Message:
        required: true
      DeployToCMS:
        type: boolean
        description: Deploy To CMS
        required: true
      DeployToVercel:
        type: boolean
        description: Deploy To Vercel
        required: true
      userEnv:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      DeployToCMS: ${{ github.event.inputs.DeployToCMS }}
      DeployToVercel: ${{ github.event.inputs.DeployToVercel }}
    steps:
    - name: DeployToCMS
      if: ${{ github.event.inputs.DeployToCMS  == 'true'}}
      run: echo "${{ github.event.inputs.Message }} - $DeployToCMS - $DeployToVercel"
      
    - name: DeployToVercel
      if: ${{ github.event.inputs.DeployToVercel  == 'true'}}
      run: echo "${{ github.event.inputs.Message }} - $DeployToCMS - $DeployToVercel"
