name: deploy-to-dev-cms-vercel
on:
  # Description
  workflow_dispatch:
    inputs:
      start_point:
        description: 'SHA or branch name to fast-forward into hotfix'
        required: true
        default: 'refs/remotes/origin/release'
        type: string
env:
    APP_LOCATION: '/' # location of your client code

permissions:
  contents: write

jobs:
  # This workflow fast forwards the hotfix branch to the latest commit in release branch
  Fast_Forward_Hotfix_Branch_To_Release_Branch:
    environment:
      name: Dev
    runs-on: prostore-actions-runner
    steps:
      - uses: actions/checkout@v3

      - name: "start_point1"
        run: echo "${{ inputs.start_point }}'"

      - name: "start_point2"
        run: echo "${{ inputs.start_point }}'"
