name: deploy-to-dev-cms-vercel
on:
  workflow_dispatch:
    inputs:
      Name:
        type: choice
        description: Whom to greet
        options: 
        - User1
        - User2
      Message:
        required: true
      DeployToCMS:
        type: boolean
        description: Deploy To CMS
        required: true
      DeployToVercel:
        type: boolean
        description: Deploy To Vercel
        required: true
      userEnv:
        type: environment

jobs:
  greet:
    environment:
      name: develop
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.Message }} ${{ fromJSON('["", ""]')[github.event.inputs.DeployToCMS] }} ${{ github.event.inputs.Name }} ${{ github.event.inputs.userEnv }}"
