name: deploy-to-develop-environment

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        required: true
        description: Environment To Run Against
        options: 
        - develop
        - hotfix
      DeployToCMS:
        description: Deploy To CMS
        type: boolean
        default: true
        required: true
      DeployToVercel:
        description: Deploy To Vercel
        type: boolean
        default: true
        required: true

env:
  DeployToCMS: ${{ inputs.DeployToCMS }}
  DeployToVercel: ${{ inputs.DeployToVercel }}
  EnvironmentToDeploy: ${{ inputs.Environment }}

jobs:
  deploy-to-cms:
    name: "cms deploy - ${{ github.event.inputs.Environment }} environment"
    if: ${{ inputs.DeployToCMS  == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.Environment }}

    steps:
    - uses: actions/checkout@v3

    - name: Print User Inputs
      run: echo "DeployToCMS - $DeployToCMS | DeployToVercel - $DeployToVercel | Environment - $EnvironmentToDeploy | VAR1 - ${{ vars.VAR1 }}"

    - name: Environment Values
      run: echo "${{ toJSON(env) }}"

    - name: "Set Blob Path"
      run: echo "Set Blob Path"

    - name: "Login To Docker"
      run: echo "Login To Docker"

    - name: "Sync Sitecore Content and Publish"
      run: echo "Sync Sitecore Content and Publish"

    - name: "Build Image and Push"
      run: echo "Build Image and Push"

    - name: "Login To Azure"
      run: echo "Login To Azure"

    - name: "Deploy To CD"
      run: echo "Deploy To CD"

    - name: "Deploy To CM"
      run: echo "Deploy To CM"

    - name: "Deploy To ID"
      run: echo "Deploy To ID"

    - name: "Logout From Azure"
      run: echo "Logout From Azure"

    - name: "Upload Sitecore Content"
      if: ${{ vars.UPLOAD_SITECORE_CONTENT  == 'true' }}
      run: echo "Upload Sitecore Content"

  deploy-to-vercel:
    name: "vercel deploy - ${{ github.event.inputs.Environment }} environment"
    if: ${{ inputs.DeployToVercel  == 'true' }}
    needs: deploy-to-cms
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.Environment }}

    steps:
    - uses: actions/checkout@v3

    - name: Print User Inputs
      run: echo "DeployToCMS - $DeployToCMS | DeployToVercel - $DeployToVercel | Environment - $EnvironmentToDeploy | VAR1 - ${{ vars.VAR1 }}"

    - name: Environment Values
      run: echo "${{ toJSON(env) }}"

    - name: "Set Blob Path"
      run: echo "Set Blob Path"

    - name: "Vercel Pull"
      run: echo "Vercel Pull"

    - name: "Vercel Build"
      run: echo "Vercel Build"

    - name: "Vercel Deploy"
      run: echo "Vercel Deploy"

    - name: "Upload Vercel Artifacts"
      if: ${{ vars.UPLOAD_VERCEL_ARTIFACTS  == 'true' }}
      run: echo "Upload Vercel Artifacts"
