name: deploy-to-dev-cms-vercel
on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        required: true
        description: Environment To Run Against
        options: 
        - develop
      DeployToCMS:
        description: Deploy To CMS
        type: boolean
        default: true
        required: true
      DeployToVercel:
        description: Deploy To Vercel
        type: boolean
        default: true
        required: true
      #Message:
      #  required: true
      #Environment:
      #  description: 'Environment To Run Against'
      #  type: environment
      #  required: true
env:
  UserName: ${{ inputs.DeployToCMS }}
  Message: ${{ inputs.DeployToCMS }}
  DeployToCMS: ${{ inputs.DeployToCMS }}
  DeployToVercel: ${{ inputs.DeployToVercel }}
  DeployEnvironment: ${{ inputs.Environment }}
jobs:
  Deploy:
    name: "Deploy to ${{ github.event.inputs.Environment }} environment"
    #if: ${{ inputs.Environment == 'master' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.Environment }}

    steps:
    - name: Print User Inputs
      run: echo "$UserName - $Message - $DeployToCMS - $DeployToVercel - $DeployEnvironment - ${{ vars.VAR1 }}"

    - name: Output Inputs
      run: echo "${{ toJSON(env) }}"
        
    - name: DeployToCMS
      if: ${{ inputs.DeployToCMS  == 'true' }}
      run: echo "DeployToCMS => $DeployToCMS"
      
    - name: DeployToVercel
      if: ${{ inputs.DeployToVercel  == 'true' }}
      run: echo "DeployToVercel => $DeployToVercel"
