name: deploy-to-develop-environment

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        #required: true
        description: "Deployment Environment"
        options: 
        - Dev
      GitBranch:
        type: choice
        #required: true
        description: "Git Branch"
        options: 
        - develop
      DeployToCMS:
        description: "Deploy to Sitecore CMS"
        type: boolean
        default: true
        required: true
      DeployToVercel:
        description: "Deploy to Vercel"
        type: boolean
        default: true
        required: true

env:
  Environment: ${{ inputs.Environment }}
  GitBranch: ${{ inputs.GitBranch }}
  DeployToCMS: ${{ inputs.DeployToCMS }}
  DeployToVercel: ${{ inputs.DeployToVercel }}

  APP_LOCATION: '/' # location of your client code
  GITHUB_CONTEXT: ${{ toJson(github) }}  
  ACR_CD_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_CD_IMAGE }}
  ACR_CM_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_CM_IMAGE }}
  ACR_ID_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_ID_IMAGE }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  IMAGE_TAG: $("${{ github.sha }}".SubString(0, 7))

permissions:
    contents: write

jobs:
  deploy-to-cms:
    name: "Deploy to Sitecore CMS"
    if: ${{ github.event.inputs.DeployToCMS  == 'true' }}
    runs-on: prostore-actions-runner
    environment:
      name: Dev

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.GitBranch }}
        fetch-depth: 0

    - name: "Input Parameters1"
      run: echo $IMAGE_TAG

    - name: "Set Blob Path"
      run: |
          "ArtifactPath=${{ github.repository }}/${{ inputs.GitBranch }}/sitecore/$(Get-Date -Format 'MM-dd-yyyy')/$IMAGE_TAG" >> $env:GITHUB_ENV
          "CDImageNoTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-cd" >> $env:GITHUB_ENV
          "CMImageNoTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-cm" >> $env:GITHUB_ENV
          "IDImageNoTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-id" >> $env:GITHUB_ENV
          "QACDImageWithTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-cd:$IMAGE_TAG" >> $env:GITHUB_ENV
          "QACMImageWithTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-cm:$IMAGE_TAG" >> $env:GITHUB_ENV
          "QAIDImageWithTag=prdeu2svcecomm.azurecr.io/devbuild/resideo-xm1-id:$IMAGE_TAG" >> $env:GITHUB_ENV
          cp ".env.example" ".env"

    - name: "Input Parameters2"
      run: echo $CDImageNoTag:${{ env.IMAGE_TAG }}

    - name: "Input Parameters3"
      run: echo ${{ env.CDImageNoTag }}:$IMAGE_TAG
