name: deploy-to-hotfix-cms-vercel
# **What it does**: On manual trigger, it deploys hotfix branch code to Hotfix environment both for Sitecore CMS and Vercel.

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        required: true
        description: "Deployment Environment"
        options: 
        - Hotfix
      GitBranch:
        type: choice
        required: true
        description: "Git Branch"
        options: 
        - hotfix

env:
  Environment: ${{ inputs.Environment }}
  GitBranch: ${{ inputs.GitBranch }}
  DeployToCMS: true # ${{ inputs.DeployToCMS }}
  DeployToVercel: true # ${{ inputs.DeployToVercel }}

  APP_LOCATION: '/' # location of your client code
  GITHUB_CONTEXT: ${{ toJson(github) }}  
  ACR_CD_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_CD_IMAGE }}
  ACR_CM_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_CM_IMAGE }}
  ACR_ID_IMAGE: ${{ secrets.REGISTRY_URI }}/${{ secrets.ACR_ID_IMAGE }}
  NEW_IMAGE_TAG: $("${{ github.sha }}".SubString(0, 7))
  
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NPM_PKG_GITHUB_AUTH_TOKEN: ${{ secrets.NPM_PKG_GITHUB_AUTH_TOKEN }}
  GRAPHQL_PERSISTED_QUERIES_AUTH_TOKEN: ${{ secrets.GRAPHQL_PERSISTED_QUERIES_AUTH_TOKEN }}
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VAR1Value: ${{ vars.hotfixappvar }}

permissions:
    contents: read

jobs:
  deployment-configs:
    name: "1-Print User Selection"
    runs-on: ubuntu-latest
    outputs:
      Config: ${{ steps.Configs.outputs.Config }}
      CMWebDB: ${{ steps.Configs.outputs.CMWebDB }}
      CMWebCUDB: ${{ steps.Configs.outputs.CMWebCUDB }}
      CMSolrUrl: ${{ steps.Configs.outputs.CMSolrUrl }}
      ACRImage: ${{ steps.Secrets.outputs.ACRImage }}
      VAR1: ${{ steps.Secrets.outputs.VAR1 }}
      PatchingStatus: ${{ steps.cmConfigPatching.outputs.Status }}
      RestoreStatus: ${{ steps.cmConfigRestore.outputs.Status }}

    environment:
      name: Hotfix
      url: https://hauthor.prostore.resideo.com
    steps:

    - name: "Login To Azure"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_AD_SP }}

    - name: "Read Production Current State"
      run: |
          echo "Environment : $Environment"
          echo "GitBranch : ${{ inputs.GitBranch }}"

    - name: 'Read Production Configs'
      shell: pwsh
      id: Configs
      run: |
        $configVal=$(az webapp config appsettings list --name "hotfixapp" --resource-group "hotfix-sc-eu2-svcecomm-rg" --query "[?name == 'CurrentSettings'].{Value:value}"  -o tsv)
        echo "$configVal"
        echo "::set-output name=Config::$configVal"
        
        $cmWeb=$(az webapp config appsettings list --name "hotfixapp" --resource-group "hotfix-sc-eu2-svcecomm-rg" --query "[?name == 'Sitecore_ConnectionStrings_Web'].{Value:value}"  -o tsv)
        echo "$cmWeb"
        echo "::set-output name=CMWebDB::$cmWeb"
        
        $CMWebCUDB=$(az webapp config appsettings list --name "hotfixapp" --resource-group "hotfix-sc-eu2-svcecomm-rg" --query "[?name == 'Sitecore_ConnectionStrings_WebCU'].{Value:value}"  -o tsv)
        echo "$CMWebCUDB"
        echo "::set-output name=CMWebCUDB::$CMWebCUDB"
        
        $cmSolrUrl=$(az webapp config appsettings list --name "hotfixapp" --resource-group "hotfix-sc-eu2-svcecomm-rg" --query "[?name == 'Sitecore_ConnectionStrings_Solr.Search'].{Value:value}"  -o tsv)
        echo "$cmSolrUrl"
        echo "::set-output name=CMSolrUrl::$cmSolrUrl"
                
    - name: 'Read Production CM Config'
      id: Secrets
      run: |
        echo "::set-output name=ACR_CD_IMAGE::${{ secrets.ACR_CD_IMAGE }}"
        echo "::set-output name=VAR1::${{ vars.VAR1 }}"
        
    - name: 'CM Config Patching Done'
      if: true
      id: cmConfigPatching
      run: |
        echo "::set-output name=Status::true"
        
    - name: 'CM Config Patching Done'
      if: true
      id: cmConfigRestore
      run: |
        echo "::set-output name=Status::true"
    - name: 'Print Production Config'
      if: false
      run: |
        echo ${{ steps.cdApp.outputs.Config }}
    - name: Job Failed
      if: ${{ failure() && steps.getProdConfig.conclusion == 'failure' }}
      run: |
        echo 'Job Failed'

  task2-cms-deploy:
    name: "2-Deploy to CMS (Staging)"   # Image Tagging, Deploy to Staging, CM Config Patching
    needs: [deployment-configs]
    if: true # ${{ github.event.inputs.DeployToCMS  == 'true' }}
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    runs-on: ubuntu-latest
    env:
      Config: ${{ needs.deployment-configs.outputs.Config }}
      CMWebDB: ${{ needs.deployment-configs.outputs.CMWebDB }}
      CMWebCUDB: ${{ needs.deployment-configs.outputs.CMWebCUDB }}
      CMSolrUrl: ${{ needs.deployment-configs.outputs.CMSolrUrl }}
      ACRImage: ${{ needs.deployment-configs.outputs.ACRImage }}
      AllConfigs: ${{ needs.deployment-configs.outputs.CMSolrUrl}}
      VAR1: ${{needs.deployment-configs.outputs.VAR1 }}
      PatchingStatus: ${{needs.deployment-configs.outputs.PatchingStatus}}
      RestoreStatus: ${{needs.deployment-configs.outputs.RestoreStatus}}
    steps:
    - name: 'Read Production Config'
      run: |
        echo ${{ needs.deployment-configs.outputs.AllConfigs }}
        echo "$Config"
        echo "$CMWebDB"
        echo "$CMWebCUDB"
        echo "$CMSolrUrl"
        echo "$ACRImage"
        echo "$VAR1"

    - name: 'VAR1 Value'
      run: |
        echo "VAR1Value : $VAR1Value"

    - name: 'CM Config Patching Done'
      if: true
      id: cmConfigPatching
      run: |
        echo "::set-output name=Status::true"
        
    - name: 'CM Config Patching Done'
      if: true
      id: cmConfigRestore
      run: |
        echo "::set-output name=Status::true"
    - name: 'Print Production Config'
      if: true
      run: |
        echo ${{ steps.cdApp.outputs.Config }}
    - name: Job Failed
      if: ${{ failure() && steps.getProdConfig.conclusion == 'failure' }}
      run: |
        echo 'Job Failed'
  task3-cms-content-sync:
    name: "3-Sync CMS Content"
    needs: [task2-cms-deploy]
    if: true
    runs-on: ubuntu-latest
    environment:
      name: Hotfix
    steps:
    - name: "User Selection"
      run: |
          echo "Environment : ${{ inputs.Environment }}"

  task4-vercel-preview-deploy:
    name: "4-Deploy to Vercel (Preview)"
    runs-on: ubuntu-latest
    needs: [task3-cms-content-sync]
    if: |
      always() && (needs.task3-cms-content-sync.result == 'success')
    environment:
      name: Hotfix
      url: https://resideo-hotfix-preview.vercel.app/us/en/pro

    steps:
    - name: "Print Current Settings from Job1"
      run: |
          echo ${{ needs.task2-cms-deploy.outputs.Config }}

    - name: 'VAR1 Value'
      run: |
        echo "VAR1Value : $VAR1Value"

# Testing Preview site here

  task5-approve-deployment:
    name: "5-Validate Preview Deployment"
    needs: [task4-vercel-preview-deploy]
    if: |
      always() && !failure() 
    runs-on: ubuntu-latest
    environment:
      name: Hotfix
    steps:
    - name: "User Selection"
      run: |
          echo "Environment : ${{ inputs.Environment }}"

  task6-swap-cms:
    name: "6-Promote CMS Staging to Production"
    needs: [task2-cms-deploy, task5-approve-deployment]
    if: |
      always() && !failure()
    runs-on: ubuntu-latest
    environment:
      name: HotfixNoApproval
    steps:
    - name: "User Selection"
      run: |
          echo "Environment : ${{ inputs.Environment }}"

    - name: 'VAR1 Value'
      run: |
        echo "VAR1Value : $VAR1Value"


  task7-swap-vercel:
    name: "7-Promote Vercel Preview to Production"
    needs: [task6-swap-cms]
    if: |
      always() && !failure()
    runs-on: ubuntu-latest
    environment:
      name: HotfixNoApproval
    steps:
    - name: "User Selection"
      run: |
          echo "Environment : ${{ inputs.Environment }}"
          
  task8-deployment-completed:
    name: "8-Deployment Successful"
    needs: [task6-swap-cms, task7-swap-vercel]
    if: |
      always() && !failure()
    runs-on: ubuntu-latest
    environment:
      name: HotfixNoApproval
    steps:
    - name: "Deployment Successful"
      run: |
          echo "${{ inputs.Environment }} Deployment Successful"

    - name: 'VAR1 Value'
      run: |
        echo "VAR1Value : $VAR1Value"

          
  task9-rollback-on-error:
    name: "9-Rollback On Error"
    needs: [task2-cms-deploy, task8-deployment-completed]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    environment:
      name: HotfixNoApproval
    env:
      Config: ${{needs.task2-cms-deploy.outputs.Config}}
      PatchingStatus: ${{needs.task2-cms-deploy.outputs.PatchingStatus}}
      RestoreStatus: ${{needs.task2-cms-deploy.outputs.RestoreStatus}}
    steps:
    - name: "Rollback CM Config"
      if: ${{ env.PatchingStatus == 'true' }}
      run: |
          echo "Rollback $Environment CM Config changes"
    
    - name: "No Rollback Required"
      if: ${{ env.PatchingStatus != 'true' }}
      run: |
          echo "No Rollback Required"
