name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/rde-resideo/gitflow/releases/latest | jq '.tag_name' | sed 's/\"//g')"
    - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
        
