name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Variables
      run: |
        echo "TagBranch=$(git branch --contains "$GITHUB_SHA")" >> $GITHUB_ENV
        echo "TagBranch ${TagBranch}"

    - name: Output Variables
      run: |
        echo "${env:TagBranch}"
        
