name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        commits_url: ${{ github.repository.commits_url }}
      run: |
        echo "1 : event name : ${{ github.event_name }}"
        echo "2 : commits_url : $commits_url"
        echo "3 : git_commits_url : ${{ github.repository.git_commits_url }}"
        echo "4 : sha : ${{ github.sha }}"
        echo "$GITHUB_CONTEXT.repository.commits_url"
        echo "$GITHUB_CONTEXT.repository.git_commits_url"
        echo "$GITHUB_CONTEXT.sha"
        echo "$GITHUB_CONTEXT"
