name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        commits_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/git/commits/$GITHUB_SHA
      run: |
        echo "1 : event name : ${{ github.event_name }}"
        echo "2 : commits_url : $commits_url"
        
