name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
env:
  ValidTagBranchMsg: "You are good to proceed with build! Code commit branch is : ${{ steps.TagBranch.outputs.BranchName}}."
  InvalidTagBranchMsg: "Please create your Tag with master or develop branch to Proceed with Build! : ${{ steps.TagBranch.outputs.BranchName}}"
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get Branch Name for Commit
      id: TagBranch
      run: |
         echo '::set-output name=action_echo::enabled'
         echo '::echo::off'
         echo "::set-output name=BranchName::$(curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/branches-where-head" | jq -r '.[].name')"
         
    - name: Proceed With Build
      if: ${{ steps.TagBranch.outputs.BranchName == 'master' || steps.TagBranch.outputs.BranchName == 'develop'}}
      run: |
        echo "$ValidTagBranchMsg"
        
    - name: Can Not Proceed With Build
      if: ${{ steps.TagBranch.outputs.BranchName != 'master' && steps.TagBranch.outputs.BranchName != 'develop'}}
      run: |
        echo "::warning:: $InvalidTagBranchMsg"
