name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get Branch Name for Commit 
      id: TagBranch
      run: |
         echo "::set-output name=BranchName::$(curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/branches-where-head" | jq -r '.[].name')"
    - name: confirm release tag
      run: |
        echo ${{ steps.TagBranch.outputs.BranchName }}