name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get Branch Name for Commit
      id: TagBranch
      run: |
         echo "::set-output name=BranchName::$(curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/branches-where-head" | jq -r '.[].name')"
    - name: Proceed with Build
      if: ${{ steps.TagBranch.outputs.BranchName == 'master' || steps.TagBranch.outputs.BranchName == 'develop'}}
      run: |
        echo "You are good to proceed with build!"
        
    - name: Do not Proceed with Build
      if: ${{ steps.TagBranch.outputs.BranchName != 'master' || steps.TagBranch.outputs.BranchName != 'develop'}}
      run: |
        echo "::warning:: You can not proceed with this build. Please create your Tag with master or develop branch to Proceed with Build!"