name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        CommitUrl: "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/git/commits/$GITHUB_SHA"
      run: |
        echo "event name : ${{ github.event_name }}"
        echo "CommitUrl : ${{ env.CommitUrl }}"
    - name: Get branch name
        id: tagbranch
        env:
            CommitUrl: "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/git/commits/$GITHUB_SHA"
        run: |
          echo "::set-output name=branchname::$(curl -s $CommitUrl | jq '.tag_name' | sed 's/\"//g')"
    - name: confirm release tag
        run: |
          echo ${{ steps.tagbranch.outputs.branchname }}
        
