name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://github.com/rde-resideo/gitflow/commit/90d4572c64e5d740471b5855c648de284d24734f )"
    - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
        
