name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Find Branch Name
      run: |
          ./.github/scripts/set-env-variables.ps1
      shell: pwsh
        
