name: Build_On_Banch_And_Tag
on:
  push:
    tags:        
      - resideo_*.*
jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Find Branch Name
      run: |
          ./.github/scripts/set-env-variables.ps1
      shell: pwsh
        
