name: update-hotfix-branch-ff

on:
  workflow_dispatch:
    inputs:
      TargetGitBranch:
        type: choice
        required: true
        description: "Targer Git Branch (fast forward)"
        options: 
        - hotfix
      SourceGitBranch:
        type: choice
        required: true
        description: "Source Git Branch"
        options: 
        - release
      GitSHA:
        description: "Git SHA or commit id from release branch"
        type: string
        default: 'refs/remotes/origin/release'
        required: true

permissions:
  contents: write

env:
  TargetGitBranch: ${{ inputs.TargetGitBranch }}
  SourceGitBranch: ${{ inputs.SourceGitBranch }}
  GitSHA: ${{ inputs.GitSHA }}

jobs:
  update-hotfix-branch-from-release-branch:
    name: "Deploy to Sitecore CMS"
    #if: ${{ github.event.inputs.GitSHA  != '' }}
    runs-on: ubuntu-latest

    steps:
    - name: "Input Parameters"
      run: echo "${{ toJSON(env) }}"

    - uses: actions/checkout@v3
      with:
          ref: release
          fetch-depth: 0
    - name: "Update hotfix branch to release branch commit id - ${{ inputs.GitSHA }}"
      run: |
          echo Reset Git Branch
          git add . && git reset --hard
          echo Git Checkout Release Branch
          git checkout --force -B release ${{ inputs.GitSHA }}
          echo Git Checkout Hotfix Branch
          git checkout --force -B hotfix refs/remotes/origin/hotfix
          echo Git Fast-forward Hotfix Branch To Release Branch
          git merge release --ff-only
          echo Git Push Hotfix Branch
          git push origin hotfix
          echo Done
